#############################################
###   使用する言語と version                 ###
#############################################
runtime: php81

#############################################
###   URI を設定する                        ###
#############################################
handlers:
# ルートにアクセスされた時、index.html を表示
- url: /
  static_files: www/index.html
  upload: www/index.html
  # secure: always

# 3 ページだけなので、限定的に設定する
- url: /company
  static_files: www/company.html
  upload: www/company.html
  # secure: always

- url: /student
  static_files: www/student.html
  upload: www/student.html
  # secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

# # 下層フォルダ自体にアクセスされた時、各フォルダの index.html を表示
# - url: /(.+)/$
#   static_files: \1/index.html
#   upload: .+/index\.html$
#   secure: always

# # 静的ファイル
# - url: /(.+\.(html|css|js|gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(html|css|js|gif|png|jpg)$
#   # secure: always

# 上記以外は index.php
- url: .*
  script: auto
  secure: always


#############################################
###   App Engine の性能を設定する            ###
#############################################

# # 一番性能が低い 28インスタンス時間
# instance_class: F1

# # 待機するインスタンスは最大１つ 3000ms超えたらインスタンス起動
# automatic_scaling:
#   min_idle_instances: automatic
#   max_idle_instances: 1
#   min_pending_latency: 3000ms
#   max_pending_latency: automatic
#   max_concurrent_requests: 80