name: PR作成時に label 付与
run-name: PR作成時に label 付与
on:
  pull_request:
    # types: [opened, reopened]
    types: 
      - opened
      - reopened
jobs:
  addLabelsByBranch:
    name: PR Labeler
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/pr-labeler-action@v4
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/assign-author@v1
